import { site } from './site';

// Per-page metadata with canonical URL and matching Open Graph / Twitter tags.
const DEFAULT_IMAGE = '/og'; // 1200×630 logo card, generated by app/og/route.js

export function buildMetadata({
  title,
  description = site.description,
  path = '/',
  image = DEFAULT_IMAGE,
  type = 'website',
} = {}) {
  const fullTitle = title ? `${title} · ${site.name}` : `${site.name} — ${site.tagline}`;
  const images = [{ url: image, width: 1200, height: 630 }];
  return {
    title: fullTitle,
    description,
    alternates: { canonical: path },
    openGraph: { title: fullTitle, description, url: path, siteName: site.name, type, images },
    twitter: { card: 'summary_large_image', title: fullTitle, description, images },
  };
}

export const noIndex = { robots: { index: false, follow: false } };
