import { Bricolage_Grotesque, Inter } from 'next/font/google';
import { Providers } from '@/components/common/Providers';
import { ICON_SRC } from '@/lib/brand';
import { buildMetadata } from '@/lib/seo';
import { site } from '@/lib/site';
import '@/styles/globals.css';

const sans = Inter({ subsets: ['latin'], variable: '--font-sans', display: 'swap' });
const display = Bricolage_Grotesque({ subsets: ['latin'], variable: '--font-display', display: 'swap' });

export const metadata = {
  metadataBase: new URL(site.url),
  ...buildMetadata(),
  applicationName: site.name,
  icons: {
    icon: { url: ICON_SRC, type: 'image/png' },
    apple: { url: '/apple-icon', type: 'image/png', sizes: '180x180' }, // generated by app/apple-icon.js
  },
  keywords: ['dog seizure tracker', 'canine epilepsy', 'dog seizure log', 'pet medication reminder', 'CLAWKIT'],
};

export const viewport = {
  themeColor: '#f9f8f2',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${sans.variable} ${display.variable}`}>
      <body className="font-sans">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
